env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
rules:
  camelcase:
    - 'error'
    - properties: 'never'
  lines-between-class-members:
    - 'error'
    - always
  indent:
    - 'error'
    - 2
  quotes:
    - 'error'
    - single
  semi:
    - 'error'
    - always
  require-jsdoc:
    - 'warn'
