name: gitStream Workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gitstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run GitStream
        uses: linear-b/gitstream@v0.1.0
        with:
          config-path: .cm/gitstream.cm
