name: SonarCloud Scan

on:
  pull_request:
    branches:
      - main
      - feature/*
      - bugfix/*

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=my_project_key \
          -Dsonar.organization=my_organization \
          -Dsonar.sources=./src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
